// Current capabilities — what the system has TODAY, scored on tech + operational maturity (0-10)
export const CURRENT_CAPABILITIES = [
  {
    name: "County-Record Scraping Pipeline",
    category: "Data Acquisition",
    techScore: 7, opScore: 6,
    description: "Autonomous multi-source scraper targeting 35+ Florida county assessor, tax collector, probate court, foreclosure, and auction sites. Uses LLM web-search + cloud browser engine for extraction, with Railway-based cron scheduling and Supabase upsert deduplication.",
    examples: [
      "Scrape Miami-Dade tax deed sale calendar and extract 200+ properties per run",
      "Pull probate court filings from Hillsborough County and identify inherited properties",
      "Extract code violation lists from Jacksonville city portal with property addresses and violation types",
    ],
  },
  {
    name: "AI Deal Scoring (0–100)",
    category: "AI & Analytics",
    techScore: 9, opScore: 8,
    description: "Every property receives an AI-generated 0-100 score based on equity potential, distress severity, location quality, market trends, and repair cost ratio. Uses InvokeLLM with structured JSON schema output for consistent, comparable scores.",
    examples: [
      "Score a pre-foreclosure in Orlando at 87/100 with breakdown: equity 9, distress 8, location 7, trend 8, repair 6",
      "Batch-score 500 active properties overnight and flag all 80+ scores as 'hot deals'",
      "Compare two properties side-by-side with AI reasoning for why one scores higher",
    ],
  },
  {
    name: "Ownership Chain & Heir Tracing",
    category: "Data Enrichment",
    techScore: 8, opScore: 7,
    description: "Traces current, previous, and potential-heir owners through probate records and property transfers. Builds a complete ownership timeline with transfer dates, sale prices, and relationship to property.",
    examples: [
      "Trace a property back 3 owners to identify the original 1995 purchase at $45K (now worth $310K)",
      "Identify 4 potential heirs of a deceased owner through probate filings",
      "Show ownership transfer from LLC to individual with quitclaim deed reference",
    ],
  },
  {
    name: "AI Negotiation Assistant",
    category: "AI & Analytics",
    techScore: 9, opScore: 8,
    description: "Sellers get an AI coach that analyzes every offer against market data, suggests counter-offer amounts with reasoning, and scripts the negotiation conversation. Unique in the industry — no competitor has this.",
    examples: [
      "Analyze a $180K offer on a property worth $250K ARV and recommend countering at $210K with 3 reasoning points",
      "Detect a lowball offer pattern from an investor and suggest a firm response strategy",
      "Generate a professional counter-offer email with market comps as justification",
    ],
  },
  {
    name: "Smart Contract Escrow (Polygon)",
    category: "Blockchain",
    techScore: 8, opScore: 7,
    description: "Solidity 0.8.20 escrow contracts deployed on Polygon blockchain. Manages earnest money deposits, digital signatures, contingency tracking, and fund release. Full audit logging of all on-chain actions.",
    examples: [
      "Deploy an escrow contract for a $200K purchase with $5K earnest money and 30-day closing window",
      "Release funds to seller only after inspection passes — all conditions enforced on-chain",
      "View complete audit trail: deployed → signed → funded → inspected → released",
    ],
  },
  {
    name: "Autonomous Investor Outreach Engine",
    category: "Outreach",
    techScore: 8, opScore: 7,
    description: "AI scrapes investor contacts (name, company, email, target markets) from public directories, generates personalized outreach emails with correct names and property data, and sends with automated follow-up sequences.",
    examples: [
      "Scrape 50 new investor leads from BiggerPockets and send personalized intro emails within 1 hour",
      "Auto-follow-up with non-responders after 7 days with a different angle (new distressed inventory)",
      "Track which investors respond and auto-update their lead status to 'responded'",
    ],
  },
  {
    name: "Autonomous Seller/Owner Outreach",
    category: "Outreach",
    techScore: 7, opScore: 6,
    description: "Generates personalized outreach to distressed property owners with skip-traced contact info. Includes follow-up automation, opt-out tracking, and outreach status management.",
    examples: [
      "Send 100 personalized letters to tax-delinquent owners with their property details and a cash offer",
      "Auto-follow-up with owners who haven't responded in 14 days with a revised offer",
      "Track outreach status: new → contacted → responded → opted_out",
    ],
  },
  {
    name: "Market Analytics & Trend Pricing",
    category: "AI & Analytics",
    techScore: 7, opScore: 6,
    description: "Syncs regional market data: average price, price/sqft, days-on-market, distress counts, and ROI trends. Uses LLM web search for real-time data.",
    examples: [
      "Show that Miami-Dade avg price/sqft increased 8% YoY, signaling strong seller market",
      "Display distress count by county: Broward 1,200, Miami-Dade 950, Palm Beach 600",
      "Track 30-day DOM trend to help investors time their offers",
    ],
  },
  {
    name: "Property Image Ingestion",
    category: "Data Enrichment",
    techScore: 4, opScore: 3,
    description: "Backend functions exist to fetch and ingest property images from scraped sources. Currently partial — not wired to county GIS imagery or Google Street View Static API.",
    examples: [
      "Extract <img> src from a property listing page and store in PropertyImage entity",
      "Attempt to fetch exterior photo from county assessor parcel page",
      "Store image with type classification (street_view, satellite, interior, exterior)",
    ],
  },
  {
    name: "Address Normalization & Dedupe",
    category: "Data Quality",
    techScore: 8, opScore: 8,
    description: "Normalizes addresses and deduplicates using geohash proximity. '123 Main St' and '123 Main Street' are merged. Batch merge function cleans existing duplicates.",
    examples: [
      "Normalize '123 Main St.' → '123 Main Street' and merge with existing record",
      "Detect two listings within 10m geohash proximity and merge into one richer record",
      "Batch-clean 5,000 duplicate properties across 35 sources in one run",
    ],
  },
  {
    name: "Digital Signature System (ESIGN)",
    category: "Legal & Compliance",
    techScore: 8, opScore: 8,
    description: "Own digital signature system — no third-party dependency. ESIGN Act + FL Electronic Commerce Act compliant. SHA-256 cryptographic hashing, IP/timestamp/user-agent audit trail, downloadable legal certificate.",
    examples: [
      "Sign a purchase agreement digitally with full legal weight — admissible in court",
      "Generate a tamper-evident signature certificate with document hash and signer identity",
      "Verify a signature hasn't been tampered with by comparing document hashes",
    ],
  },
  {
    name: "Legal Disclosure Generator (FL)",
    category: "Legal & Compliance",
    techScore: 8, opScore: 8,
    description: "Auto-generates all Florida-mandated disclosure forms: Seller Property Disclosure (§689.26), Lead-Based Paint (pre-1978, federal Title X), Radon (§404.056), HOA (§720.401), Mold. Ready for digital signature.",
    examples: [
      "Generate all 5 FL disclosure forms for a 1965 property in one click",
      "Auto-detect pre-1978 construction and include lead-based paint disclosure",
      "Generate HOA disclosure only when property is in an HOA community",
    ],
  },
  {
    name: "Deal Calculator (Profit Split)",
    category: "Analytics",
    techScore: 8, opScore: 8,
    description: "Models wholesale assignment, fix & flip, BRRRR, and buy & hold. Calculates MAO (70% rule), projected profit, ROI, cash-on-cash return, and per-person profit splits with industry benchmarks.",
    examples: [
      "Calculate MAO for a flip: ARV $300K × 70% - $40K rehab - $15K closing = $155K max offer",
      "Compare wholesale vs flip vs BRRRR on the same property side-by-side",
      "Show that a $180K offer is 92% of fair value based on industry benchmarks",
    ],
  },
  {
    name: "Bidding System (with Proxy Bids)",
    category: "Transactions",
    techScore: 7, opScore: 7,
    description: "Investors place bids on properties with optional proxy bidding (auto-increment up to max). Bid notifications, expiry tracking, and acceptance flow.",
    examples: [
      "Place a proxy bid up to $200K — system auto-increments to beat competing bids",
      "Notify seller when a new bid arrives and show all active bids ranked by amount",
      "Auto-expire bids after 7 days and notify bidders their bid expired",
    ],
  },
  {
    name: "Saved Searches & Deal Alerts",
    category: "User Tools",
    techScore: 7, opScore: 7,
    description: "Investors save search filters and receive alerts for new matches, price drops, auction dates, and outbid notifications. Alerts via email and in-app.",
    examples: [
      "Save a search for 'pre-foreclosures in Miami-Dade under $200K' and get email alerts",
      "Get notified instantly when another investor outbids you on a watched property",
      "Receive alert 48 hours before an auction date for a tracked property",
    ],
  },
  {
    name: "Skip Trace (LLM Fallback)",
    category: "Data Enrichment",
    techScore: 5, opScore: 4,
    description: "Uses InvokeLLM with web search to find owner phone numbers, emails, and relatives from public sources. Fallback only — no production skip-trace API integration yet.",
    examples: [
      "Search for 'John Smith, owner of 123 Main St, Miami' and find a likely phone number",
      "Identify 3 possible relatives of a deceased property owner",
      "Find a business email for an LLC-owned property through public filings",
    ],
  },
  {
    name: "Title Risk Assessment",
    category: "Legal & Compliance",
    techScore: 6, opScore: 5,
    description: "Entity exists to track lien totals, mortgage balances, judgments, code liens, HOA delinquency, and tax delinquency. AI analysis generates risk level (low/medium/high/critical).",
    examples: [
      "Flag a property with $45K in liens and $180K mortgage as 'high' title risk",
      "Show that a property is tax-delinquent with $12K owed — critical risk",
      "AI-analyze title risk and recommend whether to proceed or require title clearance",
    ],
  },
  {
    name: "Property Cross-Referencing",
    category: "Data Quality",
    techScore: 7, opScore: 7,
    description: "Cross-references properties across multiple distress lists (liens + tax + code + DOM + severity) to identify properties appearing on multiple lists — highest motivation indicators.",
    examples: [
      "Identify a property on both the tax-delinquent AND code-violation lists — double distress",
      "Stack 4 distress signals on one property: pre-foreclosure + tax delinquent + code violation + 180 DOM",
      "Score a property higher because it appears on 3 separate distress lists",
    ],
  },
  {
    name: "Daily Scrape Pipeline (Automated)",
    category: "Automation",
    techScore: 7, opScore: 7,
    description: "Fully automated daily pipeline: scrape → normalize → dedupe → upsert → score → trace ownership → sync analytics. Runs on cron with no human intervention.",
    examples: [
      "Run at 2 AM daily, process 5,000+ properties, and have fresh inventory by morning",
      "Auto-retry failed sources with exponential backoff, continue past individual failures",
      "Log every scrape job with properties found/new/updated counts",
    ],
  },
  {
    name: "System Health & Auto-Heal",
    category: "Automation",
    techScore: 7, opScore: 7,
    description: "Nightly integrity sweep validates system health, re-runs failed sources, resets error states, and expires stale inventory. Auto-pauses sources after 3 consecutive failures.",
    examples: [
      "Detect 3 failed scrapes on a source and auto-pause it for 24 hours with alert",
      "Re-run a failed source automatically on the next cycle and recover",
      "Expire properties not verified in 30 days to keep inventory fresh",
    ],
  },
  {
    name: "SEO / AEO Optimization",
    category: "Growth",
    techScore: 8, opScore: 8,
    description: "JSON-LD structured data on all content pages, dynamic sitemap generation, robots.txt, Google Search Console sync, and Answer Engine Optimization for AI search visibility.",
    examples: [
      "Auto-generate JSON-LD schema for every property detail page for Google rich results",
      "Submit dynamic sitemap to Google with all active property URLs for maximum indexation",
      "Sync Search Console performance data: clicks, impressions, CTR, top queries",
    ],
  },
  {
    name: "Google Sheets Sync",
    category: "Integration",
    techScore: 6, opScore: 6,
    description: "Two-way sync between property data and Google Sheets for investors who prefer spreadsheet workflows. Export filtered properties with all fields.",
    examples: [
      "Export all Miami-Dade pre-foreclosures to a Google Sheet with 20+ columns",
      "Sync investor pipeline to a shared Google Sheet for team collaboration",
      "Auto-update sheet when new properties are scraped or scores change",
    ],
  },
  {
    name: "Supabase Integration",
    category: "Integration",
    techScore: 7, opScore: 7,
    description: "Primary database for heavy scraping data. Supabase handles high-volume property records while Base44 manages AI scoring, workflows, and user-facing logic.",
    examples: [
      "Store 50,000+ scraped properties in Supabase with indexed queries",
      "Sync from Supabase to Base44 entities for UI rendering and scoring",
      "Use Supabase Storage for property imagery (S3-compatible)",
    ],
  },
  {
    name: "Blockchain Wallet Management",
    category: "Blockchain",
    techScore: 7, opScore: 6,
    description: "Generate and import Polygon wallets for smart contract deployment. Secure secret management for private keys. Balance and network status monitoring.",
    examples: [
      "Generate a new Polygon wallet for the platform's escrow operations",
      "Import an existing wallet with private key for contract deployment",
      "Monitor wallet balance and alert when MATIC is low for gas",
    ],
  },
  {
    name: "AI Contract Document Generation",
    category: "Blockchain",
    techScore: 7, opScore: 6,
    description: "AI generates legal documents (purchase agreements, assignment contracts, closing statements) from smart contract terms. Documents are ready for digital signature.",
    examples: [
      "Generate a purchase agreement from smart contract terms with all parties and contingencies",
      "Create an assignment contract for a wholesale deal with fee structure",
      "Generate a closing statement with prorations and disbursements",
    ],
  },
  {
    name: "Follow-Up Automation",
    category: "Outreach",
    techScore: 7, opScore: 6,
    description: "Configure automated follow-up sequences for investor leads and property owners. Set frequency, enable/disable per contact, and track next follow-up date.",
    examples: [
      "Set a 7-day follow-up cadence for investor leads who haven't responded",
      "Auto-schedule next follow-up date and send when the date arrives",
      "Disable follow-ups for contacts who opt out",
    ],
  },
  {
    name: "Investor Pipeline Management",
    category: "User Tools",
    techScore: 7, opScore: 7,
    description: "Investors track deals through 7 stages: lead → underwriting → offer → contract → closing → rehab → exit. Exit strategy tracking, projected vs actual profit, and notes.",
    examples: [
      "Move a property from 'lead' to 'underwriting' after initial analysis",
      "Track a flip deal: acquisition $155K, rehab $40K, ARV $300K, projected profit $105K",
      "Compare projected vs actual profit on closed deals for performance analysis",
    ],
  },
  {
    name: "Seller Property Posting",
    category: "User Tools",
    techScore: 6, opScore: 6,
    description: "Sellers post distressed properties free with AI pricing suggestions. Properties go live in the marketplace for investors to discover and bid on.",
    examples: [
      "A seller posts a inherited property in Tampa and gets AI-suggested asking price of $185K",
      "Seller uploads property photos and description, property appears in marketplace within minutes",
      "Seller receives 3 bids within 48 hours and uses AI negotiation to evaluate them",
    ],
  },
  {
    name: "Agent Dashboard",
    category: "User Tools",
    techScore: 7, opScore: 6,
    description: "Full toolkit for licensed FL real estate agents: deal pipeline, commission tracking, disclosure generation, digital signatures, co-marketing agreements, MLS comps, listing syndication, and FAQ.",
    examples: [
      "Agent generates all FL disclosure forms for a listing in one click and signs digitally",
      "Track $45K in earned commissions across 5 closed deals with payout status",
      "Create a co-marketing agreement with an investor and sign digitally",
    ],
  },
  {
    name: "Full System Test Lab",
    category: "Operations",
    techScore: 8, opScore: 8,
    description: "50+ tests across 7 categories: scraping, scoring, outreach, smart contracts, legal, bidding, and system health. Individual test buttons with pass/warn/fail + error explanations. 'Run All' for end-to-end testing.",
    examples: [
      "Run all 50+ backend function tests and see which pass, warn, or fail with error messages",
      "Test the digital signature function and verify it returns a valid certificate",
      "Test the legal disclosure generator and verify all 5 FL forms are generated",
    ],
  },
];