// Master Enrichment System — 15 categories, 100+ features
// Used by AdminEnrichmentUpgrades page to track installation status

export const ENRICHMENT_CATEGORIES = [
  {
    id: "structural",
    name: "Property-Level Physical Data",
    icon: "Building2",
    description: "Structural details, permits, code violations, condition assessment",
    features: [
      { name: "Full structural details", why: "Determines repair scope before site visit", advantage: "Eliminates surprise rehab costs", technology: "County permit history + LLM-extracted MLS/assessor data + satellite roof analysis", status: "planned" },
      { name: "Permit history", why: "Shows what's been updated vs original", advantage: "Avoids code-violation surprises", technology: "County building department API scraping + document OCR", status: "planned" },
      { name: "Code violation details", why: "Signals distress severity", advantage: "Negotiation leverage; accurate lien estimates", technology: "County code enforcement portal scraping + LLM classification", status: "planned" },
      { name: "Renovation/modification history", why: "Identifies value-add and compliance risk", advantage: "Spots hidden ARV upside or legal exposure", technology: "Permit data + aerial imagery change detection", status: "planned" },
      { name: "Energy efficiency rating", why: "Affects insurance and utility costs", advantage: "Lower holding costs; marketing advantage", technology: "Energy audit databases + assessor fields + AI inference", status: "planned" },
      { name: "Environmental hazards", why: "Health/legal liability; remediation cost", advantage: "Avoids catastrophic rehab overruns", technology: "EPA Superfund/brownfield databases + state DEP + LLM cross-reference", status: "planned" },
      { name: "Property condition AI assessment", why: "Remote evaluation without site visit", advantage: "Scales to thousands of properties", technology: "Computer vision model on property photos", status: "planned" },
    ],
  },
  {
    id: "title_legal",
    name: "Ownership & Title Intelligence",
    icon: "FileText",
    description: "Ownership chain, mortgage/lien detail, foreclosure timeline, probate, tax delinquency",
    features: [
      { name: "Full ownership chain", why: "Reveals equity position and motivation", advantage: "Equity calculation; motivation inference", technology: "County clerk/recorder scraping + document parsing LLM", status: "active" },
      { name: "Mortgage & lien detail", why: "Determines payoff and short-sale viability", advantage: "Accurate equity math; subject-to opportunities", technology: "County recorder + MERS data + title company APIs", status: "planned" },
      { name: "Foreclosure timeline", why: "Pinpoints process stage", advantage: "Times outreach perfectly", technology: "County clerk daily scraping + foreclosure tracking services", status: "planned" },
      { name: "Probate status", why: "Identifies motivated heirs", advantage: "Highest-conversion outreach channel", technology: "Obituary scraping + probate court docket scraping", status: "active" },
      { name: "Divorce filings", why: "Distress signal; forced sale", advantage: "Early distress detection", technology: "County family court docket scraping", status: "planned" },
      { name: "Bankruptcy filings", why: "Automatic stay affects everything", advantage: "Pre-discharge negotiation windows", technology: "PACER federal bankruptcy court API", status: "planned" },
      { name: "Tax delinquency detail", why: "Direct path to acquisition", advantage: "Pre-auction acquisition opportunity", technology: "County tax collector API + tax sale portal scraping", status: "planned" },
      { name: "HOA status", why: "Hidden costs and legal constraints", advantage: "Avoids HOA surprise costs", technology: "HOA management data + county lien records", status: "planned" },
      { name: "Judgment & UCC filings", why: "Hidden encumbrances affecting title", advantage: "Clean title assessment", technology: "County clerk UCC/judgment search", status: "planned" },
    ],
  },
  {
    id: "valuation",
    name: "Valuation & Financial Modeling",
    icon: "DollarSign",
    description: "Multi-source AVM, comps, ARV, rehab costs, holding costs, insurance, equity",
    features: [
      { name: "Multi-source AVM", why: "No single AVM is accurate", advantage: "±3% confidence vs ±10%", technology: "API aggregation + weighted ensemble model", status: "planned" },
      { name: "Comparable sales (live)", why: "Gold standard for ARV", advantage: "Defensible offer price", technology: "MLS data + county recorder + ATTOM/BatchData APIs", status: "planned" },
      { name: "Price-per-sqft trends", why: "Shows micro-market direction", advantage: "Timing entry/exit", technology: "Time-series analysis of county sales data", status: "planned" },
      { name: "Rental estimates (LTR + STR)", why: "Cash-flow viability and exit flexibility", advantage: "Validates BRRRR/buy-hold; STR-legal properties", technology: "Rentometer + AirDNA + Airbnb scraping + LLM area analysis", status: "active" },
      { name: "ARV calculation", why: "Single most important flip number", advantage: "Removes human error", technology: "Comp adjustment algorithm + rehab cost AI model", status: "planned" },
      { name: "Rehab cost estimate (itemized)", why: "Budget precision", advantage: "Prevents budget overruns", technology: "AI model trained on regional contractor pricing", status: "planned" },
      { name: "Holding cost projection", why: "Total cost of carry", advantage: "Accurate all-in cost; profit margin integrity", technology: "API-driven cost aggregation + duration estimation", status: "planned" },
      { name: "Insurance estimate", why: "FL insurance is a deal-killer", advantage: "Kills bad deals before offer", technology: "Insurance quoting APIs + flood zone data", status: "planned" },
      { name: "Property tax projection", why: "Taxes jump after purchase in FL", advantage: "Prevents cash-flow surprises", technology: "County millage rates + assessment cap modeling", status: "planned" },
      { name: "Utility cost estimates", why: "Holding cost accuracy", advantage: "Complete carry cost picture", technology: "Utility company average consumption data", status: "planned" },
      { name: "CDD & special assessment fees", why: "Hidden $2k–$8k/yr costs in FL", advantage: "Kills deals that look good without CDD", technology: "County CDD records + HOA disclosure scraping", status: "planned" },
      { name: "Equity calculation", why: "Core metric for off-market quality", advantage: "Instant go/no-go", technology: "Automated lien aggregation + AVM blending", status: "active" },
    ],
  },
  {
    id: "neighborhood",
    name: "Neighborhood & Location Intelligence",
    icon: "MapPin",
    description: "Demographics, employment, walkability, crime, schools, hospitals, amenities, flood, hurricane, sinkhole",
    features: [
      { name: "Demographic profile", why: "Determines tenant quality and exit buyer pool", advantage: "Filters out war-zone properties", technology: "Census ACS API + Esri demographic data", status: "planned" },
      { name: "Employment centers", why: "Drives rental demand", advantage: "Identifies high-demand submarkets", technology: "Google Places API + BLS + commute time matrix", status: "planned" },
      { name: "Walkability & transit", why: "Affects rental demand", advantage: "Higher demand = lower vacancy", technology: "Walk Score API + Google transit data", status: "planned" },
      { name: "Detailed crime statistics", why: "Tenant safety, insurance, liability", advantage: "Avoids high-vacancy areas", technology: "CrimeMapping API + FBI UCR + local police open data", status: "active" },
      { name: "School ratings (all assigned)", why: "#1 driver of homebuyer demand", advantage: "Higher exit resale value; faster sale", technology: "GreatSchools API + FL DOE school grades", status: "active" },
      { name: "Hospital/medical access", why: "Retiree/buyer appeal in FL", advantage: "Niche market targeting", technology: "Google Places API + hospital databases", status: "planned" },
      { name: "Amenity proximity", why: "Rental and resale appeal", advantage: "Faster lease-up and sale", technology: "Google Places API + OSM data", status: "planned" },
      { name: "Future development plans", why: "Early signal of appreciation/decline", advantage: "Buy ahead of gentrification", technology: "County planning scraping + news monitoring", status: "planned" },
      { name: "Flood zone (detailed)", why: "FL deal-killer; $2k–$10k/yr impact", advantage: "Instant deal filter; accurate insurance cost", technology: "FEMA flood map API + LLM zone interpretation", status: "active" },
      { name: "Hurricane/storm risk", why: "FL-specific risk; insurance and safety", advantage: "Risk-adjusted underwriting", technology: "NOAA storm data + FEMA evacuation zones", status: "planned" },
      { name: "Sinkhole risk", why: "FL-specific catastrophic risk", advantage: "Avoids uninsurable properties", technology: "FL Geological Survey sinkhole database", status: "planned" },
      { name: "Wetlands & environmental constraints", why: "Limits development/renovation scope", advantage: "Avoids permit denial surprises", technology: "USFWS wetlands mapper + FL DEP layers", status: "planned" },
    ],
  },
  {
    id: "market",
    name: "Market & Trend Data",
    icon: "TrendingUp",
    description: "Appreciation trends, DOM, inventory, seasonal patterns, migration, job growth, investor activity",
    features: [
      { name: "Market appreciation trend", why: "Direction and velocity of value", advantage: "Times market entry/exit", technology: "County sales time-series + Case-Shiller-style index", status: "planned" },
      { name: "Days on market trend", why: "Liquidity indicator; buyer demand", advantage: "Predicts time-to-exit", technology: "MLS + county sales data aggregation", status: "planned" },
      { name: "Inventory levels", why: "Buyer's vs seller's market signal", advantage: "Offer aggressiveness calibration", technology: "MLS feed + portal scraping aggregation", status: "planned" },
      { name: "Seasonal patterns", why: "Timing optimization", advantage: "Buy low, sell high seasonally", technology: "Multi-year seasonal decomposition of sales data", status: "planned" },
      { name: "Migration patterns", why: "Demand source prediction", advantage: "Identifies emerging hot markets", technology: "USPS change-of-address + Census migration + U-Haul pricing", status: "planned" },
      { name: "Job growth & economic indicators", why: "Fundamental demand driver", advantage: "Long-term appreciation confidence", technology: "BLS + state economic data + news monitoring", status: "planned" },
      { name: "Population growth", why: "Long-term demand", advantage: "Identifies 5-10 year appreciation markets", technology: "Census projections + state demographer data", status: "planned" },
      { name: "New construction pipeline", why: "Supply pressure on existing homes", advantage: "Avoids oversupplied price points", technology: "Building permit data + construction tracking", status: "planned" },
      { name: "Investor activity heatmap", why: "Competition intensity", advantage: "Finds low-competition pockets", technology: "County sales buyer-type classification + LLC cross-reference", status: "planned" },
      { name: "Rental market trends", why: "Cash-flow projection accuracy", advantage: "Validates buy-hold; predicts rent growth", technology: "Census ACS + rental platform data aggregation", status: "planned" },
    ],
  },
  {
    id: "distress",
    name: "Distress & Motivation Signals",
    icon: "AlertTriangle",
    description: "Pre-foreclosure tracking, tax sale countdown, vacancy detection, death records, divorce, bankruptcy",
    features: [
      { name: "Pre-foreclosure timeline tracking", why: "Exact process stage", advantage: "Perfect-timed outreach", technology: "County clerk daily monitoring + foreclosure tracking APIs", status: "active" },
      { name: "Tax sale countdown", why: "Urgency clock", advantage: "Pre-auction acquisition", technology: "Tax collector API + auction portal scraping", status: "planned" },
      { name: "Vacancy detection", why: "Most motivated sellers; easiest access", advantage: "Highest-conversion target", technology: "Utility data + mail carrier data + AI imagery analysis", status: "planned" },
      { name: "Maintenance neglect signals", why: "Distress visible from space", advantage: "Remote distress scoring at scale", technology: "Computer vision on satellite/street imagery", status: "planned" },
      { name: "Death record cross-reference", why: "Probate opportunity", advantage: "Earliest possible probate detection", technology: "Obituary aggregation + SSDI + public death notice scraping", status: "active" },
      { name: "Divorce filing monitoring", why: "Forced sale; timeline pressure", advantage: "Pre-listing acquisition", technology: "County family court docket scraping", status: "planned" },
      { name: "Bankruptcy monitoring", why: "Distress + automatic stay awareness", advantage: "Pre-discharge negotiation window", technology: "PACER API", status: "planned" },
      { name: "Job loss indicators", why: "Mortgage default predictor", advantage: "Pre-foreclosure lead generation", technology: "BLS data + news monitoring + WARN act notices", status: "planned" },
      { name: "Life event triggers", why: "Life events drive property sales", advantage: "Proactive outreach before listing", technology: "Social media monitoring + public records + news", status: "planned" },
      { name: "Code violation escalation", why: "Mounting municipal pressure", advantage: "Negotiation leverage", technology: "Code enforcement portal monitoring", status: "planned" },
      { name: "HOA foreclosure", why: "Often overlooked distress channel", advantage: "Low-competition acquisition", technology: "County lien records + HOA attorney filings", status: "planned" },
      { name: "Expired/withdrawn listings", why: "Proven motivation", advantage: "Warm leads with known asking price", technology: "MLS expired listing reports via broker", status: "planned" },
      { name: "FSBO monitoring", why: "Direct-to-seller, no agent commission", advantage: "Higher margin deals", technology: "Platform scraping + LLM listing extraction", status: "planned" },
    ],
  },
  {
    id: "skip_tracing",
    name: "Contact & Skip Tracing",
    icon: "UserSearch",
    description: "Owner phone, email, current address, social media, relatives & heirs, neighbors, age, employer",
    features: [
      { name: "Owner phone numbers", why: "Direct outreach capability", advantage: "Reaches seller directly", technology: "Skip tracing services (TLO, LexisNexis, Accurint, BatchData)", status: "planned" },
      { name: "Owner email addresses", why: "Multi-channel outreach", advantage: "Higher response rate", technology: "People search APIs + social media", status: "planned" },
      { name: "Owner current address", why: "Absentee owners = high motivation", advantage: "Targets out-of-state landlords", technology: "USPS address forwarding + people search APIs", status: "planned" },
      { name: "Social media profiles", why: "Relationship-building context", advantage: "Personalized outreach", technology: "Social media API scraping (compliant) + OSINT tools", status: "planned" },
      { name: "Relatives & heirs", why: "Probate outreach; alternate contacts", advantage: "Reaches heirs who may not know they own property", technology: "Genealogy databases + obituary cross-reference", status: "active" },
      { name: "Neighbors", why: "Tip network; partnership potential", advantage: "Word-of-mouth lead generation", technology: "County property records + reverse address lookup", status: "planned" },
      { name: "Owner age & life stage", why: "Life-stage motivation inference", advantage: "Targets likely downsizers/retirees", technology: "People search APIs + voter registration", status: "planned" },
      { name: "Employer & income estimate", why: "Affordability and motivation context", advantage: "Offer calibration", technology: "LinkedIn scraping + business entity records", status: "planned" },
      { name: "Previous addresses", why: "Stability indicator; relocation pattern", advantage: "Identifies likely-to-move owners", technology: "People search address history", status: "planned" },
    ],
  },
  {
    id: "competitive",
    name: "Competitive Intelligence",
    icon: "Swords",
    description: "Competing investor activity, wholesaler assignments, flip tracking, new construction, MLS activity",
    features: [
      { name: "Competing investor activity", why: "Market intelligence; avoids overpaying", advantage: "Informs offer strategy", technology: "County sales buyer pattern analysis + LLC tracing", status: "planned" },
      { name: "Wholesaler assignment activity", why: "Market temperature; deal flow visibility", advantage: "Identifies wholesalers to partner with", technology: "County recorder assignment document scraping", status: "planned" },
      { name: "Flip activity tracking", why: "Market competition and profit benchmarks", advantage: "Validates flip viability in area", technology: "County sales data matching algorithm", status: "planned" },
      { name: "New construction competition", why: "Supply pressure on resales", advantage: "Avoids competing with new builds", technology: "Building permit data + construction tracking", status: "planned" },
      { name: "MLS activity", why: "Real-time market pulse", advantage: "Offer calibration; exit timing", technology: "MLS feed via broker", status: "planned" },
      { name: "Off-market activity estimate", why: "True market size (not just MLS)", advantage: "Full market picture", technology: "County sales vs MLS comparison", status: "planned" },
    ],
  },
  {
    id: "risk",
    name: "Risk Assessment",
    icon: "ShieldAlert",
    description: "Insurance claims history, flood insurance cost, wind mitigation, special assessments, environmental contamination",
    features: [
      { name: "Insurance claims history (CLUE)", why: "Hidden risk; uninsurability", advantage: "Avoids uninsurable properties", technology: "CLUE database access (LexisNexis)", status: "planned" },
      { name: "Flood insurance cost projection", why: "FL deal-critical cost", advantage: "Accurate holding cost; deal filter", technology: "FEMA flood data + insurance quoting APIs", status: "planned" },
      { name: "Wind mitigation status", why: "Insurance premium reduction", advantage: "Lower holding costs; value-add", technology: "Assessor fields + inspection inference", status: "planned" },
      { name: "Special assessment risk", why: "Hidden $5k–$50k liabilities", advantage: "Avoids surprise costs", technology: "County commission minutes + CDD meeting scraping", status: "planned" },
      { name: "Zoning change risk", why: "Use-change impact on value", advantage: "Avoids adverse changes; spots upside", technology: "County planning department monitoring", status: "planned" },
      { name: "Eminent domain risk", why: "Forced sale at below-market", advantage: "Avoids or capitalizes on takings", technology: "DOT project databases + county commission records", status: "planned" },
      { name: "Environmental contamination", why: "Liability and value impact", advantage: "Avoids toxic adjacency", technology: "EPA EnviroFacts + state DEP databases", status: "planned" },
      { name: "Insurance availability", why: "FL market instability", advantage: "Avoids uninsurable areas", technology: "Insurance market monitoring + carrier territory data", status: "planned" },
    ],
  },
  {
    id: "ai_analysis",
    name: "AI-Powered Analysis",
    icon: "Brain",
    description: "Predictive distress scoring, opportunity score, auto rehab scope, exit strategy, ROI projection, optimal offer",
    features: [
      { name: "Predictive distress scoring", why: "Proactive vs reactive lead gen", advantage: "Finds deals before competitors", technology: "Gradient-boosted model on historical distress outcomes", status: "planned" },
      { name: "Investment opportunity score", why: "Single number to rank 10,000 properties", advantage: "Prioritizes outreach at scale", technology: "Weighted ensemble model with explainable factors", status: "planned" },
      { name: "Auto-generated rehab scope", why: "Instant contractor-ready scope", advantage: "Eliminates manual scope writing", technology: "Computer vision + LLM scope generation + regional pricing DB", status: "planned" },
      { name: "Comparable property matching", why: "Appraiser-grade accuracy", advantage: "Defensible ARV; lender-ready", technology: "ML comp adjustment model (feature-weighted, distance-decayed)", status: "planned" },
      { name: "Market timing prediction", why: "Optimizes entry and exit", advantage: "Captures appreciation; avoids downturns", technology: "Time-series forecasting (ARIMA/Prophet) + leading indicators", status: "planned" },
      { name: "Exit strategy recommendation", why: "Data-driven strategy selection", advantage: "Maximizes per-deal profit", technology: "Rule engine + ML model on historical exit outcomes", status: "planned" },
      { name: "Risk-adjusted ROI projection", why: "Probability-weighted returns", advantage: "Realistic profit expectations", technology: "Monte Carlo simulation engine + sensitivity analysis", status: "planned" },
      { name: "Natural-language investor summary", why: "Instant human-readable deal brief", advantage: "Scales analysis to thousands of properties", technology: "LLM with structured data injection", status: "active" },
      { name: "Comparable rent analysis", why: "Accurate rental income projection", advantage: "Validates cash-flow deals", technology: "Rental platform data + ML adjustment model", status: "planned" },
      { name: "Neighborhood gentrification prediction", why: "Buy ahead of the curve", advantage: "3-5x appreciation capture", technology: "ML model on permit trends, business openings, price velocity", status: "planned" },
      { name: "Optimal offer price recommendation", why: "Removes emotion and guesswork", advantage: "Higher close rate + maintained margin", technology: "Trained on historical offer→acceptance outcomes", status: "planned" },
    ],
  },
  {
    id: "visual_spatial",
    name: "Visual & Spatial Data",
    icon: "Image",
    description: "Aerial imagery, street-level, 3D models, lot boundaries, topography, solar exposure, view analysis",
    features: [
      { name: "Current aerial imagery", why: "Lot size, condition, surroundings verification", advantage: "Remote due diligence", technology: "Nearmap + Google Earth + county GIS imagery", status: "planned" },
      { name: "Historical aerial imagery", why: "Shows improvements, neglect, additions", advantage: "Identifies unpermitted work; condition trend", technology: "Nearmap historical archive + USGS imagery", status: "planned" },
      { name: "Street-level imagery", why: "Exterior condition, neighborhood quality", advantage: "Virtual drive-by at scale", technology: "Google Street View API + Mapillary", status: "planned" },
      { name: "3D property model", why: "Remote measurement and visualization", advantage: "Remote scope assessment", technology: "Photogrammetry from aerial + street imagery", status: "planned" },
      { name: "Lot boundary visualization", why: "Confirms lot size, easements, setbacks", advantage: "Identifies development potential", technology: "County GIS parcel data + mapping overlay", status: "planned" },
      { name: "Topography & elevation", why: "Drainage issues, buildable area", advantage: "Avoids flood-prone lots; identifies buildable land", technology: "USGS elevation data (LiDAR) + county DEM", status: "planned" },
      { name: "Solar exposure analysis", why: "Solar panel viability", advantage: "Identifies solar upside", technology: "Sun-path analysis on aerial imagery + roof plane detection", status: "planned" },
      { name: "View analysis", why: "Premium pricing justification", advantage: "Accurate premium pricing", technology: "3D viewshed analysis from elevation + building heights", status: "planned" },
      { name: "Neighborhood visual quality score", why: "Area quality at a glance", advantage: "Remote area assessment", technology: "Computer vision model on neighborhood imagery", status: "planned" },
    ],
  },
  {
    id: "legal_compliance",
    name: "Legal & Compliance",
    icon: "Scale",
    description: "Title insurance, survey availability, zoning verification, STR legality, rental restrictions, building code",
    features: [
      { name: "Title insurance quote", why: "Closing cost accuracy", advantage: "Complete cost picture", technology: "Title company API integration", status: "planned" },
      { name: "Survey availability", why: "Avoids $500–$1,500 survey cost", advantage: "Cost savings", technology: "County records + title company data", status: "planned" },
      { name: "Zoning verification", why: "Development feasibility", advantage: "Confirms highest-and-best-use", technology: "County zoning API + LLM code interpretation", status: "active" },
      { name: "Short-term rental legality", why: "Airbnb/VRBO viability", advantage: "Validates STR exit strategy", technology: "Municipal code scraping + STR ordinance databases", status: "planned" },
      { name: "Rental restriction check", why: "Buy-hold viability", advantage: "Avoids non-rentable properties", technology: "HOA document OCR + county recorded restrictions", status: "planned" },
      { name: "Building code compliance", why: "Permit/CO risk", advantage: "Avoids post-rehab CO problems", technology: "Code comparison engine + permit history", status: "planned" },
      { name: "Easement & encroachment detection", why: "Usability and value impact", advantage: "Avoids use limitations", technology: "Title search + GIS overlay + aerial encroachment detection", status: "planned" },
    ],
  },
  {
    id: "financial_modeling",
    name: "Financial & Investment Modeling",
    icon: "Calculator",
    description: "Full deal calculator, sensitivity analysis, stress testing, portfolio optimization, financing comparison, tax modeling",
    features: [
      { name: "Full deal calculator", why: "Complete deal analysis", advantage: "One-click deal evaluation", technology: "Computation engine (partially built)", status: "active" },
      { name: "Sensitivity analysis", why: "Stress-tests assumptions", advantage: "Identifies fragile deals", technology: "Monte Carlo + tornado chart sensitivity engine", status: "planned" },
      { name: "Stress testing", why: "Downside protection", advantage: "Avoids catastrophic losses", technology: "Scenario modeling engine", status: "planned" },
      { name: "Portfolio optimization", why: "Risk-adjusted portfolio returns", advantage: "Maximizes portfolio-level returns", technology: "Modern portfolio theory optimization (mean-variance)", status: "planned" },
      { name: "Financing comparison", why: "Optimal capital structure", advantage: "Maximizes ROI per deal", technology: "Lender API integration + comparison engine", status: "planned" },
      { name: "Tax implication modeling", why: "After-tax returns", advantage: "True net profit", technology: "Tax code engine + CPA rule integration", status: "planned" },
      { name: "Cash flow projection (10yr)", why: "Long-term hold analysis", advantage: "Validates buy-hold deals", technology: "DCF model with configurable assumptions", status: "planned" },
      { name: "Exit timing optimizer", why: "Maximizes IRR", advantage: "Data-driven exit timing", technology: "IRR-maximization algorithm across hold periods", status: "planned" },
    ],
  },
  {
    id: "alerts",
    name: "Real-Time Monitoring & Alerts",
    icon: "Bell",
    description: "Price drops, new distress events, status changes, market shifts, competitor activity, saved search alerts",
    features: [
      { name: "Price drop alerts", why: "Re-evaluate at new price", advantage: "Catches newly-attractive deals", technology: "MLS + portal monitoring + entity webhook", status: "planned" },
      { name: "New distress event alerts", why: "First-mover on new distress", advantage: "Beats competitors by days", technology: "County clerk daily monitoring + alert engine", status: "planned" },
      { name: "Status change notifications", why: "Pipeline tracking", advantage: "Timely intervention", technology: "Entity subscription + workflow triggers", status: "active" },
      { name: "Market shift alerts", why: "Market timing signals", advantage: "Portfolio-level decisions", technology: "Market data aggregation + threshold alerts", status: "planned" },
      { name: "Competitor activity alerts", why: "Competitive intelligence", advantage: "Adjusts strategy", technology: "Buyer pattern tracking + alert engine", status: "planned" },
      { name: "Saved search alerts", why: "Never miss a match", advantage: "Automated lead generation", technology: "Entity create trigger + criteria matcher workflow", status: "active" },
      { name: "Life event triggers", why: "Proactive outreach timing", advantage: "Pre-emptive acquisition", technology: "Public records monitoring + watchlist cross-reference", status: "planned" },
    ],
  },
  {
    id: "data_sources",
    name: "Data Source Integration Stack",
    icon: "Database",
    description: "60+ data sources — county records, MLS, portals, aggregators, skip tracing, rental, school, crime, flood, imagery",
    features: [
      { name: "County records (67 FL counties)", why: "Primary source of property data", advantage: "Direct from source; no third-party delay", technology: "Daily scraping engine (self-hosted Playwright) + API where available", status: "active" },
      { name: "MLS via broker", why: "Gold standard listing data", advantage: "Accurate comps, DOM, listing history", technology: "RETS/RESO Web API feed", status: "planned" },
      { name: "National portals", why: "Broad market coverage", advantage: "Cross-reference and validate", technology: "Scraping + unofficial APIs", status: "active" },
      { name: "Data aggregators (ATTOM, CoreLogic, etc.)", why: "Enriched data not available from counties", advantage: "Pre-processed, structured data", technology: "Paid API subscriptions", status: "planned" },
      { name: "Skip tracing services", why: "Direct contact data", advantage: "Reaches sellers directly", technology: "API integration (TLO, LexisNexis, BatchData)", status: "planned" },
      { name: "Rental data (Rentometer, AirDNA)", why: "Rental income estimates", advantage: "Validates cash-flow deals", technology: "API + scraping", status: "planned" },
      { name: "School data (GreatSchools, FL DOE)", why: "School ratings drive demand", advantage: "Higher exit resale value", technology: "API + scraping", status: "planned" },
      { name: "Crime data (CrimeMapping, FBI UCR)", why: "Tenant safety and area quality", advantage: "Avoids high-vacancy areas", technology: "API + open data", status: "planned" },
      { name: "Flood & environment (FEMA, NOAA, EPA)", why: "FL-specific risk data", advantage: "Accurate insurance and risk costs", technology: "Government APIs", status: "planned" },
      { name: "Imagery (Nearmap, Google Earth, Mapillary)", why: "Remote due diligence", advantage: "Visual verification at scale", technology: "API subscriptions + scraping", status: "planned" },
      { name: "Court records (PACER, FL courts)", why: "Distress signal detection", advantage: "Early distress identification", technology: "Scraping + PACER API", status: "planned" },
      { name: "Obituaries & death records", why: "Probate lead generation", advantage: "Earliest probate detection", technology: "Scraping + aggregation", status: "active" },
    ],
  },
];

export const STATUS_META = {
  active: { label: "Active", color: "emerald" },
  planned: { label: "Planned", color: "amber" },
  needs_api: { label: "Needs API", color: "red" },
};