// Future capabilities — what the system CAN or SHOULD have
export const FUTURE_CAPABILITIES = [
  // Data Acquisition
  { name: "Skip-Trace API Integration (TLO / IRBsearch)", category: "Data Enrichment", description: "Production-grade skip-trace API for finding owner phone numbers, emails, and relatives. Industry standard for real estate — far more reliable than LLM web search.", examples: ["Look up phone number for 500 property owners in one batch API call", "Find 3 relatives of a deceased owner with contact info for each", "Get verified email addresses with 90%+ deliverability rate"] },
  { name: "Stealth & Proxy Layer", category: "Data Acquisition", description: "playwright-stealth + residential proxy rotation for scraping hard targets (realforeclose, Auction.com). Currently blocked by WAF on datacenter IPs.", examples: ["Scrape realforeclose.com through a residential proxy without 403 blocks", "Rotate 50 proxy IPs to avoid rate limiting on aggressive sources", "Bypass Cloudflare bot detection with stealth fingerprint masking"] },
  { name: "Driving-for-Dollars Map Mode", category: "Data Acquisition", description: "Mobile map interface to tag off-market properties in the field. Auto-creates draft records with geocode, photo, and notes. DealMachine parity.", examples: ["Drive through a neighborhood, tap properties on the map to flag as distressed", "Auto-geocode the tagged property and create a draft record with photo", "Sync field acquisitions to the main database when back online"] },
  { name: "ATTOM / BatchData Property Enrichment", category: "Data Enrichment", description: "Third-party property data API for mortgage balance, equity position, lien details, and propensity-to-default scoring. PropStream parity.", examples: ["Enrich 1,000 properties with mortgage balance and equity position in one API call", "Get ATTOM's propensity-to-default score and factor it into our AI scoring", "Pull lien details: type, amount, filing date, holder for every property"] },
  { name: "Nationwide Expansion (All 50 States)", category: "Data Acquisition", description: "Currently FL-only. Expand scraping to all 50 states with state-specific source configurations and compliance rules.", examples: ["Scrape Georgia tax deed sales and Texas foreclosure auctions", "Add California probate filings and New York code violations", "Auto-detect state from property address and apply correct disclosure templates"] },
  { name: "Real-Time Property Monitoring", category: "Data Acquisition", description: "Continuous monitoring of properties via satellite imagery changes, permit filings, and tax status updates. Detect changes before they hit public listing.", examples: ["Detect a new roof permit filing and flag the property as 'in progress'", "Satellite image shows a new pool — update property value estimate", "Tax payment status changes from 'paid' to 'delinquent' — trigger alert"] },

  // AI & Machine Learning
  { name: "Predictive Distress Scoring", category: "AI & Analytics", description: "AI predicts which properties will become distressed BEFORE they hit public records. Uses market trends, owner age, mortgage age, and payment patterns.", examples: ["Flag a property as 'likely distressed in 90 days' based on mortgage age + market decline", "Predict foreclosure probability at 73% for a property with 4 missed payments", "Alert investors to pre-distress opportunities before competitors see them"] },
  { name: "AI Property Condition Assessment", category: "AI & Analytics", description: "AI analyzes satellite and street view images to estimate property condition, roof age, and exterior repair needs without a physical inspection.", examples: ["Analyze a Google Street View image and estimate roof is 15+ years old", "Detect visible exterior damage (cracks, peeling paint, overgrown yard) from satellite", "Generate a repair cost estimate from image analysis: $25K-$35K"] },
  { name: "AI Property Description Generator", category: "AI & Analytics", description: "AI writes compelling, SEO-optimized property descriptions from images + data. Eliminates manual writing for sellers and agents.", examples: ["Generate a 200-word description from 5 property photos + square footage data", "Write 3 description variants optimized for different buyer personas", "Auto-generate listing descriptions in Spanish for Miami market"] },
  { name: "Virtual Renovation Visualizer", category: "AI & Analytics", description: "AI generates before/after images showing what a distressed property could look like after renovation. Helps investors visualize potential.", examples: ["Upload a photo of a distressed kitchen and show a renovated $30K version", "Generate 3 renovation styles: modern, traditional, luxury", "Show estimated post-renovation value increase from the visualized changes"] },
  { name: "Investor Portfolio Optimizer", category: "AI & Analytics", description: "AI recommends which properties an investor should buy based on their portfolio, goals, and risk tolerance. Like a robo-advisor for real estate.", examples: ["Recommend 5 properties that complement an investor's existing 3-property portfolio", "Suggest diversifying: 'You're over-concentrated in Miami-Dade, consider 2 Broward deals'", "Calculate optimal portfolio allocation: 60% flips, 30% BRRRR, 10% wholesale"] },
  { name: "Neighborhood Trend Prediction", category: "AI & Analytics", description: "AI predicts neighborhood appreciation/depreciation 1-5 years out using permit activity, business openings, school ratings, and demographic shifts.", examples: ["Predict Wynwood will appreciate 12% in 3 years based on permit activity + retail growth", "Flag a neighborhood as 'declining' based on increasing code violations + decreasing owner-occupancy", "Recommend buying in 'emerging' neighborhoods before prices spike"] },
  { name: "AI Chatbot (24/7 Support)", category: "AI & Analytics", description: "Conversational AI assistant for investors, sellers, and agents. Answers questions, searches properties, generates offers, and guides users through workflows.", examples: ["Investor asks 'Find me 3 fix-and-flip deals in Tampa under $150K' and gets instant results", "Seller asks 'How much is my house worth?' and gets an instant AI estimate", "Agent asks 'What disclosures do I need for a 1965 property?' and gets the answer"] },
  { name: "Rehab Cost Estimator (AI)", category: "AI & Analytics", description: "AI estimates rehab costs from property condition, photos, and local contractor rates. More accurate than manual estimation.", examples: ["Estimate $32K rehab for a 1,500 sqft property needing full renovation in Orlando", "Break down costs: roof $8K, kitchen $12K, bathrooms $7K, paint $3K, flooring $2K", "Compare rehab costs across markets: Orlando $32K vs Miami $45K for same scope"] },

  // Legal & Compliance
  { name: "KYC / AML Verification", category: "Legal & Compliance", description: "Know Your Customer + Anti-Money Laundering verification for smart contract participants. Required for blockchain-based real estate transactions.", examples: ["Verify investor identity with ID document + selfie before allowing smart contract participation", "Run AML check against sanctions lists before releasing escrow funds", "Generate compliance report for each transaction for regulatory audit"] },
  { name: "Remote Online Notarization (RON)", category: "Legal & Compliance", description: "Florida-legal remote online notarization integrated into the platform. Sign and notarize documents 100% online.", examples: ["Notarize a deed transfer remotely with a licensed FL notary via video call", "Generate a notarized document with digital seal and audit trail", "Schedule a RON session for closing without anyone traveling"] },
  { name: "Title Search API", category: "Legal & Compliance", description: "Automated title search integration to pull lien, mortgage, and judgment data. Replaces manual title searches.", examples: ["Pull complete title history for a property in 30 seconds via API", "Identify all liens, judgments, and encumbrances before making an offer", "Generate a title report PDF for the buyer's lender"] },
  { name: "FL License Verification Gate", category: "Legal & Compliance", description: "Verify FL real estate license numbers against DBPR database before granting agent access. Ensures only licensed agents use agent tools.", examples: ["Agent enters license number SL3456789 — system verifies with DBPR in real-time", "Block unverified users from accessing MLS comps and commission tracking", "Auto-suspend agent access if license expires or is revoked"] },
  { name: "Fair Housing Compliance Audit", category: "Legal & Compliance", description: "Automated audit of all outreach, marketing, and listing descriptions for fair housing compliance. Flags discriminatory language.", examples: ["Scan an outreach email and flag 'perfect for a young family' as potentially discriminatory", "Auto-replace flagged language with compliant alternatives", "Generate a compliance report for all marketing materials sent this quarter"] },
  { name: "Data Retention & Deletion (GDPR/CCPA)", category: "Legal & Compliance", description: "Automated data retention policies and right-to-deletion workflows. Comply with privacy regulations.", examples: ["Auto-delete owner contact data 90 days after deal closes unless retained with consent", "Process a CCPA deletion request and remove all user data within 30 days", "Generate a data inventory report for compliance audit"] },
  { name: "State-Specific Disclosure Library", category: "Legal & Compliance", description: "Expand beyond FL to all 50 states' disclosure requirements. Auto-detect state from address and generate correct forms.", examples: ["Generate California Natural Hazard Disclosure for a LA property", "Generate Texas Seller's Disclosure Notice for a Houston property", "Auto-include mold disclosure in states that require it (22+ states)"] },

  // Blockchain & Smart Contracts
  { name: "Tokenized Real Estate (NFT Deeds)", category: "Blockchain", description: "Tokenize property deeds as NFTs on Polygon. Enable fractional ownership and secondary market trading of real estate.", examples: ["Tokenize a $300K property into 1,000 shares at $300 each — investors buy fractions", "Enable secondary market trading of property tokens on a DEX", "Distribute rental income to token holders automatically via smart contract"] },
  { name: "Escrow-as-a-Service API", category: "Blockchain", description: "Offer our smart contract escrow as an API to other platforms. Monetize the blockchain infrastructure.", examples: ["A competitor platform integrates our escrow API for their transactions", "Charge $50 per escrow deployment via API usage", "White-label the escrow for brokerages under their brand"] },
  { name: "Smart Contract Security Auditing", category: "Blockchain", description: "Automated security scanning of all deployed smart contracts. Detect vulnerabilities before exploitation.", examples: ["Run Slither static analysis on every deployed contract and flag issues", "Auto-audit contract for reentrancy, overflow, and access control vulnerabilities", "Generate a security report certificate for each contract"] },
  { name: "Multi-Chain Support", category: "Blockchain", description: "Expand from Polygon to Ethereum, Arbitrum, and Base. Give users chain choice based on gas costs and preferences.", examples: ["Deploy escrow on Arbitrum when Polygon gas is high", "Let investors choose their preferred chain for transactions", "Cross-chain bridge for moving escrow between chains if needed"] },
  { name: "Gas Optimization Engine", category: "Blockchain", description: "AI optimizes gas usage on smart contract transactions. Saves money on every deployment and interaction.", examples: ["AI suggests waiting for low-gas window to deploy a contract, saving 40% on gas", "Batch multiple contract interactions into one transaction to save gas", "Auto-adjust gas price based on network congestion in real-time"] },

  // Outreach & Communication
  { name: "Direct Mail Automation", category: "Outreach", description: "Automated postcard and letter sending to property owners. Integration with printing/mailing services.", examples: ["Send 500 'We Buy Houses' postcards to tax-delinquent owners in one click", "Track which postcards were delivered and which bounced", "A/B test 2 postcard designs and measure response rates"] },
  { name: "SMS Outreach & Drip Campaigns", category: "Outreach", description: "SMS text messaging for higher open rates than email. Automated drip sequences with compliance (TCPA opt-out).", examples: ["Send a text to 100 owners: 'Hi John, interested in a cash offer for 123 Main St? Reply STOP to opt out'", "Auto-send follow-up text 3 days after initial contact if no response", "Track SMS response rates vs email response rates by campaign"] },
  { name: "Ringless Voicemail", category: "Outreach", description: "Drop voicemails without the phone ringing. Higher response rate than cold calls, legal in most states.", examples: ["Drop 200 voicemails to distressed owners with a personalized message", "Track which voicemails resulted in callbacks", "A/B test 3 voicemail scripts and measure callback rate"] },
  { name: "Multi-Channel Campaign Orchestration", category: "Outreach", description: "Orchestrate outreach across email, SMS, direct mail, and voicemail in one automated sequence. Maximize touchpoints.", examples: ["Day 1: Email, Day 3: SMS, Day 7: Postcard, Day 14: Voicemail, Day 21: Follow-up email", "Auto-pause sequence when owner responds and route to a human", "Track total cost per lead across all channels and optimize"] },
  { name: "CRM (Investor/Seller/Agent)", category: "Outreach", description: "Full CRM with contact management, deal tracking, task management, and communication history. Replace HubSpot for real estate.", examples: ["See complete contact history for an owner: 3 emails, 1 SMS, 1 postcard, 2 calls", "Set a task to call an owner on Tuesday and get a reminder", "Track deal stage progression with drag-and-drop kanban board"] },

  // Mobile & UX
  { name: "Native Mobile App (iOS/Android)", category: "Mobile", description: "Native mobile app with push notifications, offline mode, camera for D4$, and native performance. Beyond PWA.", examples: ["Investor gets push notification when a new high-score property matches their criteria", "Use phone camera to photograph a property while driving and auto-create a record", "Work offline in areas with no cell service and sync when reconnected"] },
  { name: "3D Property Tours", category: "Mobile", description: "Matterport-style 3D virtual tours for properties. Investors can 'walk through' remotely.", examples: ["Generate a 3D tour from 50 interior photos using AI stitching", "Embed 3D tour on property detail page for remote investors", "Measure room dimensions within the 3D tour"] },
  { name: "AR Property Measurement", category: "Mobile", description: "Augmented reality room measurement using phone camera. Investors can measure properties without a tape measure.", examples: ["Point phone at a room and get instant square footage measurement via AR", "Measure lot boundaries by walking the perimeter with GPS + AR", "Generate a floor plan from AR measurements automatically"] },
  { name: "Virtual Staging", category: "Mobile", description: "AI virtual staging for property photos. Show furnished rooms without physical staging costs.", examples: ["Upload an empty room photo and show it furnished in 3 styles", "Generate a virtual staging for a $300K property to help buyers visualize", "A/B test staged vs unstaged photos and measure inquiry rate difference"] },

  // Analytics & Reporting
  { name: "Advanced Analytics Dashboard", category: "Analytics", description: "Comprehensive analytics: deal performance, ROI tracking, market trends, outreach effectiveness, and team productivity.", examples: ["Show that investor outreach has a 4.2% response rate, up from 2.8% last month", "Track team productivity: 1,200 properties scored, 300 outreach sent, 12 deals in pipeline", "Forecast next quarter revenue based on pipeline conversion rates"] },
  { name: "Automated 1099 Tax Reporting", category: "Analytics", description: "Auto-generate 1099 forms for contractors, agents, and wholesalers at year-end. E-file with IRS.", examples: ["Generate 1099-NEC for a wholesaler who earned $8K assignment fee", "Auto-collect W-9 from contractors before first payment", "E-file all 1099s with IRS in one batch on January 31"] },
  { name: "Investor Performance Leaderboard", category: "Analytics", description: "Gamified leaderboard ranking investors by deals closed, ROI, and volume. Drives engagement and competition.", examples: ["Show top 10 investors by total profit this quarter", "Rank investors by average ROI on closed deals", "Award 'Deal of the Month' badge to highest-ROI flip"] },

  // Security & Hardening
  { name: "Penetration Testing Suite", category: "Security", description: "Automated penetration testing and vulnerability scanning. Run weekly and alert on new vulnerabilities.", examples: ["Run OWASP ZAP scan and find 3 medium-severity XSS vulnerabilities", "Test all API endpoints for authentication bypass attempts", "Generate a penetration test report for compliance audit"] },
  { name: "Rate Limiting & DDoS Protection", category: "Security", description: "Advanced rate limiting, bot detection, and DDoS mitigation. Protect against scraping and abuse.", examples: ["Block an IP sending 1,000 requests/second to the property search API", "Detect and block a bot scraping all property data in sequence", "Auto-scale during traffic spikes without downtime"] },
  { name: "Encryption at Rest (Field-Level)", category: "Security", description: "Encrypt sensitive fields (owner SSN, phone, email) at rest with field-level encryption. Beyond database-level encryption.", examples: ["Encrypt owner phone numbers so even database access doesn't reveal them", "Decrypt only when displaying to authorized admin users", "Audit log every decryption event for compliance"] },
  { name: "Multi-Factor Authentication", category: "Security", description: "MFA for all users with SMS, authenticator app, or hardware key. Required for admin and agent accounts.", examples: ["Admin must enter TOTP code from Google Authenticator to access admin dashboard", "Agent receives SMS code to verify identity before signing documents", "Hardware key (YubiKey) support for high-value smart contract operations"] },

  // Monetization & Business
  { name: "White-Label Platform", category: "Business", description: "Offer the platform white-labeled to brokerages, investment firms, and wholesalers under their own brand.", examples: ["A brokerage runs 'Elite Realty Intelligence' powered by our backend", "Custom branding, domain, and colors for each white-label client", "Charge $5K/month per white-label instance"] },
  { name: "API Marketplace", category: "Business", description: "Sell our data and scoring via API to other platforms, investors, and researchers. New revenue stream.", examples: ["A hedge fund pays $10K/month for API access to our distress scoring data", "A researcher buys 10,000 property records for a market study", "A competitor pays per-transaction for our escrow API"] },
  { name: "Lead Marketplace", category: "Business", description: "Sell verified distressed property leads to investors on a per-lead or subscription basis.", examples: ["Sell a verified tax-delinquent lead with owner contact info for $15", "Subscription: $499/month for 50 verified leads per month", "Pay-per-close: $500 when a lead results in a closed deal"] },
  { name: "Escrow Fee Monetization", category: "Business", description: "Charge a fee on every smart contract escrow transaction. Like a title company but blockchain-based.", examples: ["Charge 0.5% of transaction value as escrow fee on every deal", "Generate $1,500 in revenue on a $300K property transaction", "Volume discounts for high-volume investors"] },
];