// Prompt library — copy-paste prompts to invoke the AI to build every capability
export const PROMPT_LIBRARY = [
  {
    category: "Data Acquisition & Scraping",
    icon: "Database",
    prompts: [
      { title: "Skip-Trace API Integration", prompt: "Integrate a production skip-trace API (TLO or IRBsearch) into the platform. Create a backend function that accepts owner name + address, calls the skip-trace API, and returns phone/email/relatives. Wire it to the skipTraceOwner function as the primary method, keeping InvokeLLM web search as fallback. Add a 'Skip Trace' button on every property detail page in the admin and investor dashboards. Store results in the Owner entity. Add batch skip-trace capability for 500+ owners at once." },
      { title: "Stealth & Proxy Layer", prompt: "Add a stealth and proxy layer to the Railway scraper. Install playwright-extra + stealth plugin. Configure residential proxy rotation from a proxy provider (Bright Data or Smartproxy). Add randomized delays (2-8 seconds), human-like mouse movements, and fingerprint masking. Test against realforeclose.com and Auction.com to verify WAF bypass. Add proxy health monitoring and auto-rotation on IP block detection." },
      { title: "Nationwide Expansion", prompt: "Expand the scraping pipeline from Florida-only to all 50 states. For each state, identify the top 5 county assessor, tax collector, probate court, and foreclosure sources. Create state-specific scrape configurations. Add state detection from property address. Update the DataSource entity to support state-specific settings. Build a state coverage dashboard in admin showing which states are live, how many sources, and properties scraped per state." },
      { title: "Real-Time Property Monitoring", prompt: "Build a real-time property monitoring system. Create a workflow that runs every 4 hours and checks: (1) satellite imagery changes via Google Earth Engine API, (2) new permit filings via county APIs, (3) tax payment status changes. When a change is detected, update the property record and trigger an alert to investors watching that property. Add a 'Property Monitor' tab in the admin dashboard showing all recent changes." },
    ],
  },
  {
    category: "AI & Machine Learning",
    icon: "Brain",
    prompts: [
      { title: "Predictive Distress Scoring", prompt: "Build a predictive distress scoring model. Create a backend function that takes a property and predicts its probability of becoming distressed in the next 90 days. Use factors: mortgage age, owner age (if available), market decline trend, days since last sale, neighborhood distress rate. Use InvokeLLM with a structured prompt. Add a 'Predictive Score' field to PropertyScore entity. Display it on property detail pages with a 'Predicted Distress in X days' badge." },
      { title: "AI Property Condition Assessment", prompt: "Build an AI property condition assessment tool. Create a backend function that accepts a Google Street View URL or satellite image URL, sends it to InvokeLLM with vision capabilities, and returns: estimated roof age, visible exterior damage, yard condition, overall condition score (1-10), and estimated exterior repair cost. Store results in the Property entity. Display on property detail pages. Add a 'AI Condition Check' button in admin." },
      { title: "AI Property Description Generator", prompt: "Build an AI property description generator. Create a backend function that takes a property's data (address, sqft, beds, baths, photos, distress type) and generates 3 SEO-optimized listing descriptions (200 words each) in different tones: professional, emotional, and investment-focused. Add a 'Generate Description' button on the seller post-property page and admin property detail. Support Spanish language generation for Miami market." },
      { title: "Virtual Renovation Visualizer", prompt: "Build a virtual renovation visualizer. Use the GenerateImage integration to create before/after renovation images. Create a backend function that takes a property photo and renovation style (modern, traditional, luxury) and generates a renovated version. Display before/after slider on property detail pages. Add a 'Visualize Renovation' button in the investor dashboard." },
      { title: "Investor Portfolio Optimizer", prompt: "Build an AI investor portfolio optimizer. Create a backend function that takes an investor's current portfolio (owned properties, deal history, target markets) and recommends 5 properties that complement their portfolio. Use InvokeLLM to analyze portfolio concentration, risk, and opportunity. Display recommendations in the investor dashboard with AI reasoning for each recommendation." },
      { title: "AI Chatbot (24/7 Support)", prompt: "Build a conversational AI chatbot for the platform. Create an in-app agent that can: search properties by natural language, answer FAQ questions, generate offers, guide users through workflows, and connect to a human when needed. Use the Base44 agents system. Train it on our FAQ data, property data, and workflow documentation. Add it to every dashboard (investor, seller, agent, admin) as a floating chat widget." },
      { title: "Rehab Cost Estimator", prompt: "Build an AI rehab cost estimator. Create a backend function that takes property condition, square footage, location, and renovation scope (light/medium/full) and returns a detailed cost breakdown by category (roof, kitchen, bathrooms, flooring, paint, HVAC, plumbing, electrical). Use local contractor rates adjusted by market. Display on the deal calculator page and property detail pages." },
    ],
  },
  {
    category: "Legal & Compliance",
    icon: "Scale",
    prompts: [
      { title: "KYC / AML Verification", prompt: "Build a KYC/AML verification system for smart contract participants. Integrate a KYC provider (Jumio or Onfido). Create a backend function that: (1) collects ID document + selfie, (2) verifies identity via API, (3) runs AML check against sanctions lists, (4) stores verification status. Require KYC before smart contract participation. Add a 'Verify Identity' flow in the investor dashboard. Generate compliance reports for audit." },
      { title: "Remote Online Notarization", prompt: "Integrate remote online notarization (RON) into the platform. Use a RON provider API (Notarize.com or DocVerify). Create a backend function that: (1) schedules a RON session, (2) initiates video call, (3) records notarization, (4) stores notarized document with digital seal. Add a 'Notarize Online' button on smart contract detail page. Ensure FL RON compliance (Fla. Stat. §117.021)." },
      { title: "FL License Verification Gate", prompt: "Build a FL real estate license verification gate. Create a backend function that takes a license number and verifies it against the DBPR database (https://www.myfloridalicense.com). Add a license verification step to the agent registration flow. Only verified agents get access to agent tools (MLS comps, commission tracking, co-marketing). Auto-reverify licenses quarterly and suspend access for expired licenses." },
      { title: "Fair Housing Compliance Audit", prompt: "Build an automated fair housing compliance audit system. Create a backend function that scans all outreach emails, listing descriptions, and marketing materials for potentially discriminatory language (based on protected classes: race, color, religion, national origin, sex, familial status, disability). Flag flagged content and suggest compliant alternatives. Add a 'Compliance Check' button before sending any outreach. Generate quarterly compliance reports." },
      { title: "State-Specific Disclosure Library", prompt: "Expand the legal disclosure generator from FL-only to all 50 states. For each state, research and implement: (1) seller property disclosure requirements, (2) lead-based paint (federal, pre-1978), (3) radon, (4) mold, (5) natural hazards (earthquake zones, flood zones), (6) HOA/COA. Auto-detect state from property address. Update the generateLegalDisclosures function to accept a state parameter and generate correct forms." },
      { title: "Data Retention & Deletion (GDPR/CCPA)", prompt: "Build a data retention and deletion system. Create a backend function that: (1) defines retention policies per data type (owner contacts: 90 days post-deal, user data: per request), (2) auto-deletes expired data, (3) processes CCPA deletion requests within 30 days, (4) generates data inventory reports. Add a 'Privacy & Data' settings page for users to request their data or deletion. Add a data retention dashboard in admin." },
    ],
  },
  {
    category: "Blockchain & Smart Contracts",
    icon: "Blocks",
    prompts: [
      { title: "Tokenized Real Estate (NFT Deeds)", prompt: "Build a tokenized real estate system. Create a Solidity contract that tokenizes property deeds as ERC-721 NFTs on Polygon. Create a backend function that: (1) mints a deed NFT when a property is purchased via smart contract, (2) enables fractional ownership (ERC-20 tokens representing shares), (3) distributes rental income to token holders. Add a 'Tokenize Property' flow in the smart contracts admin. Build a secondary market trading interface." },
      { title: "Smart Contract Security Auditing", prompt: "Build an automated smart contract security auditing system. Create a backend function that runs Slither static analysis on every deployed contract before it goes live. Check for: reentrancy, integer overflow, access control, unchecked calls, timestamp dependence. Generate a security report with severity levels. Block deployment if critical vulnerabilities are found. Add a 'Security Audit' tab on smart contract detail page." },
      { title: "Multi-Chain Support", prompt: "Expand blockchain support from Polygon-only to Ethereum, Arbitrum, and Base. Update the SmartContract entity to support a 'blockchain' field with all 4 options. Create chain-specific RPC configurations. Let users choose their preferred chain. Add a gas price comparison widget showing current gas on all 4 chains. Auto-recommend the cheapest chain for each transaction." },
      { title: "Gas Optimization Engine", prompt: "Build an AI gas optimization engine. Create a backend function that: (1) monitors gas prices across Polygon/Ethereum/Arbitrum in real-time, (2) predicts optimal transaction time, (3) batches multiple contract interactions into one transaction, (4) auto-adjusts gas price based on network congestion. Add a 'Gas Optimizer' panel in the smart contracts admin. Show estimated savings from optimization." },
    ],
  },
  {
    category: "Outreach & Communication",
    icon: "Mail",
    prompts: [
      { title: "Direct Mail Automation", prompt: "Build a direct mail automation system. Integrate with a printing/mailing API (Click2Mail or Lob). Create a backend function that: (1) generates postcard/letter templates, (2) sends to a mailing API with owner address, (3) tracks delivery status. Add a 'Direct Mail' tab in admin outreach. Support postcard sizes, letter templates, and A/B testing. Track response rates and cost per lead." },
      { title: "SMS Outreach & Drip Campaigns", prompt: "Build an SMS outreach system. Integrate with Twilio. Create a backend function that: (1) sends SMS to owners, (2) handles TCPA compliance (opt-out keywords: STOP, UNSUBSCRIBE), (3) manages drip sequences, (4) tracks delivery and response. Add an 'SMS Campaign' tab in admin outreach. Support templates, personalization, and scheduled sending." },
      { title: "Ringless Voicemail", prompt: "Build a ringless voicemail system. Integrate with a ringless voicemail provider (Slybroadcast or Stratics). Create a backend function that drops voicemails to owner phone numbers without ringing. Add compliance: opt-out tracking, calling time restrictions (8am-9pm), state-specific rules. Track callback rates. Add a 'Voicemail Drop' tab in admin outreach." },
      { title: "Multi-Channel Campaign Orchestration", prompt: "Build a multi-channel campaign orchestration system. Create a campaign builder in admin that sequences outreach across email, SMS, direct mail, and voicemail. Example: Day 1: Email, Day 3: SMS, Day 7: Postcard, Day 14: Voicemail. Auto-pause when owner responds. Track total cost per lead and conversion rate per channel. Visualize the campaign as a timeline." },
      { title: "Full CRM System", prompt: "Build a full CRM for investors, sellers, and agents. Create a Contact entity with: communication history, deal associations, tasks, notes, tags. Build a kanban board for deal stage management. Add task management with reminders. Build a communication timeline showing all emails, SMS, calls, and meetings per contact. Add a 'CRM' tab in every dashboard." },
    ],
  },
  {
    category: "Mobile & UX",
    icon: "Smartphone",
    prompts: [
      { title: "Native Mobile App", prompt: "Build a native mobile app for iOS and Android using the existing PWA codebase. Add native features: push notifications (via APNs/FCM), camera integration for D4$, offline mode with local storage, native navigation gestures. Configure Base44 native app build. Test on iOS Simulator and Android Emulator. Submit to App Store and Google Play." },
      { title: "3D Property Tours", prompt: "Build a 3D property tour system. Integrate with Matterport API or use AI-based 3D reconstruction from photos. Create a backend function that generates a 3D tour from 50+ interior photos. Embed the 3D tour viewer on property detail pages. Add a '3D Tour' badge on listings that have tours. Let investors navigate the 3D space with room-to-room transitions." },
      { title: "AR Property Measurement", prompt: "Build an AR property measurement tool. Use Apple ARKit and Google ARCore for room measurement via phone camera. Create a mobile component that lets investors point their phone at a room and get instant square footage. Save measurements to the property record. Generate a floor plan from AR measurements. Add an 'AR Measure' button in the mobile app." },
      { title: "Virtual Staging", prompt: "Build a virtual staging tool. Use the GenerateImage integration to furnish empty room photos. Create a backend function that takes an empty room photo and a style (modern, traditional, luxury) and generates a furnished version. Display before/after on property detail pages. Let sellers upload photos and auto-stage them for their listing." },
    ],
  },
  {
    category: "Security & Hardening",
    icon: "Shield",
    prompts: [
      { title: "Penetration Testing Suite", prompt: "Build an automated penetration testing suite. Create a backend function that runs OWASP ZAP scans against the app weekly. Test all API endpoints for: SQL injection, XSS, authentication bypass, IDOR, CSRF. Generate a vulnerability report with severity levels. Add a 'Security Scan' tab in admin showing all findings and remediation status. Alert on critical vulnerabilities." },
      { title: "Rate Limiting & DDoS Protection", prompt: "Implement advanced rate limiting and DDoS protection. Add per-IP and per-user rate limits on all API endpoints (100 req/min for reads, 10 req/min for writes). Add bot detection via request pattern analysis. Auto-block IPs that exceed limits. Add a 'Security Monitor' dashboard in admin showing blocked IPs, rate limit hits, and bot detection stats." },
      { title: "Field-Level Encryption", prompt: "Implement field-level encryption for sensitive data. Encrypt owner SSN, phone, email, and contact_address at rest using AES-256. Create a shared encryption module. Decrypt only when displaying to authorized admin users. Audit log every decryption event. Add an 'Encryption Status' indicator in admin showing which fields are encrypted." },
      { title: "Multi-Factor Authentication", prompt: "Implement multi-factor authentication for all users. Support TOTP (Google Authenticator, Authy), SMS, and hardware keys (WebAuthn/FIDO2). Require MFA for admin and agent accounts. Add an 'Enable MFA' flow in user settings. Add a 'Security Settings' page showing MFA status, recent login history, and active sessions." },
    ],
  },
  {
    category: "Automation & Autonomy",
    icon: "Zap",
    prompts: [
      { title: "Autonomous Deal Closer", prompt: "Build an autonomous deal closer system. Create a workflow that: (1) AI identifies a high-score property, (2) generates an offer based on ARV and 70% rule, (3) sends offer to seller via outreach, (4) AI negotiates via negotiation assistant, (5) on agreement, deploys smart contract escrow, (6) coordinates inspection scheduling, (7) releases funds on inspection pass, (8) updates deed on blockchain. Human approval required at offer generation and fund release. Build a 'Autonomous Deals' dashboard in admin showing all AI-managed deals." },
      { title: "Autonomous Wholesaling Engine", prompt: "Build an autonomous wholesaling engine. Create a workflow that: (1) AI finds distressed properties, (2) generates and sends contract offers, (3) on acceptance, lists the contract in the marketplace, (4) AI matches the contract to the best investor in our network based on their portfolio and criteria, (5) sends assignment offer, (6) on acceptance, processes assignment fee. Build a 'Wholesale Engine' dashboard in admin showing all wholesale deals in progress." },
      { title: "Autonomous Follow-Up Intelligence", prompt: "Build an autonomous follow-up intelligence system. Create a backend function that analyzes each contact's response patterns, optimal timing, preferred channel, and message tone. AI decides when to follow up, which channel to use, and what to say. Continuously learns from outcomes. Replace the dumb drip campaign system with this AI-driven system. Add a 'Follow-Up AI' tab in admin showing AI decisions and outcomes." },
      { title: "Autonomous Listing Optimizer", prompt: "Build an autonomous listing optimizer. Create a workflow that runs daily and for each active listing: (1) rewrites description for SEO based on search trends, (2) adjusts asking price based on views/offers/market data, (3) reorders photos based on click data, (4) A/B tests listing variations, (5) applies the best-performing version. Add an 'Auto-Optimize' toggle on each listing. Show optimization history and performance improvements." },
    ],
  },
  {
    category: "Analytics & Reporting",
    icon: "BarChart3",
    prompts: [
      { title: "Advanced Analytics Dashboard", prompt: "Build a comprehensive analytics dashboard for admin. Include: deal performance (win rate, avg ROI, time-to-close), market trends (price/sqft, DOM, inventory), outreach effectiveness (response rate by channel, cost per lead), team productivity (properties scored, outreach sent, deals in pipeline). Use Recharts for visualizations. Add date range filters. Add a 'Analytics' tab in admin with sub-tabs for each category." },
      { title: "Automated 1099 Tax Reporting", prompt: "Build an automated 1099 tax reporting system. Create a backend function that: (1) collects W-9 from contractors/agents/wholesalers before first payment, (2) tracks total payments per person per year, (3) generates 1099-NEC forms at year-end, (4) e-files with IRS via API. Add a 'Tax Reporting' tab in admin. Show all 1099s generated, status, and filing confirmation." },
      { title: "Investor Performance Leaderboard", prompt: "Build an investor performance leaderboard. Create a backend function that ranks investors by: total deals closed, total profit, average ROI, properties won. Add a 'Leaderboard' tab in the investor dashboard. Show top 10 investors with badges (Gold, Silver, Bronze). Add a 'Deal of the Month' feature highlighting the highest-ROI deal. Make it shareable on social media." },
    ],
  },
  {
    category: "Monetization & Business",
    icon: "DollarSign",
    prompts: [
      { title: "White-Label Platform", prompt: "Build a white-label platform offering. Create a system that allows brokerages and investment firms to run our platform under their own brand. Include: custom branding (logo, colors, domain), custom user management, separate data isolation, custom pricing. Add a 'White-Label' management interface in admin. Charge $5K/month per instance. Track white-label clients, their usage, and revenue." },
      { title: "API Marketplace", prompt: "Build an API marketplace for selling our data and services. Create a public API with: property search, distress scoring, ownership chain, market analytics, skip trace. Add API key management, rate limiting, usage tracking, and billing. Create a developer portal with API docs, pricing tiers, and signup. Add an 'API Marketplace' tab in admin showing API users, usage, and revenue." },
      { title: "Lead Marketplace", prompt: "Build a lead marketplace where we sell verified distressed property leads. Create a 'Leads Store' page where investors can: browse verified leads with owner contact info, buy individual leads ($15 each), or subscribe ($499/month for 50 leads). Add lead verification scoring. Track lead purchase history. Add a 'Lead Marketplace' tab in admin showing lead inventory, sales, and revenue." },
      { title: "Escrow Fee Monetization", prompt: "Build escrow fee monetization into the smart contract system. Charge 0.5% of transaction value as escrow fee on every smart contract transaction. Add the fee to the smart contract terms. Auto-deduct from the seller's proceeds at closing. Track escrow fee revenue in admin. Add volume discounts for high-volume investors (0.3% above 10 deals/month). Show projected monthly escrow revenue based on pipeline." },
    ],
  },
  {
    category: "System Hardening & Production Grade",
    icon: "ShieldCheck",
    prompts: [
      { title: "Full System End-to-End Testing", prompt: "Build a comprehensive end-to-end test suite. For every user flow (investor signup → search → bid → win → contract → close, seller post → receive bids → negotiate → accept → close, agent verify → list → generate docs → sign → close), create an automated test that runs through the entire flow. Use the test backend function system. Add a 'E2E Tests' tab in the admin test lab. Run all E2E tests nightly and alert on failures." },
      { title: "Error Monitoring & Alerting", prompt: "Set up comprehensive error monitoring and alerting. Create a backend function that collects all errors from every function, categorizes them by severity, and sends alerts (email + in-app) for critical errors. Add an 'Error Monitor' dashboard in admin showing error trends, top errors, and affected functions. Auto-create issues for recurring errors." },
      { title: "Performance Optimization", prompt: "Optimize the entire platform for production performance. (1) Add database indexes on all frequently queried fields (property_id, seller_id, investor_id, status, state, distress_type). (2) Add caching for property listings and search results. (3) Lazy-load images with Intersection Observer. (4) Code-split all routes. (5) Add CDN for static assets. (6) Optimize all database queries to use bulk operations. Add a 'Performance' dashboard in admin showing page load times, API response times, and database query performance." },
      { title: "Backup & Disaster Recovery", prompt: "Build a backup and disaster recovery system. Create a daily backup of all Base44 entities to Supabase. Create a weekly backup of Supabase to S3. Test restore procedures quarterly. Add a 'Backup & Recovery' tab in admin showing backup status, last backup time, and restore options. Document the disaster recovery plan. Add automated alerts if backups fail." },
      { title: "Documentation & Onboarding", prompt: "Build comprehensive documentation and onboarding. Create an in-app onboarding flow for new investors, sellers, and agents with interactive walkthroughs. Create a help center with searchable articles for every feature. Add video tutorials for key flows. Create an admin documentation hub with architecture diagrams, API docs, and runbooks. Add a 'Help & Docs' link in every dashboard." },
    ],
  },
  {
    category: "Visual Polish & UX Excellence",
    icon: "Sparkles",
    prompts: [
      { title: "Full Visual Redesign — Premium Grade", prompt: "Redesign every page of the platform to premium, production-grade visual quality. Ensure: consistent design system (typography, spacing, colors, shadows), micro-interactions on every button and card, loading skeletons for all async content, empty states with illustrations, error states with helpful messaging, responsive design tested at 320px, 768px, 1024px, 1440px. Use the existing luxury design tokens. Add smooth page transitions with Framer Motion. Add a dark mode toggle." },
      { title: "Property Detail Page Redesign", prompt: "Redesign the property detail page to be the best in the industry. Include: hero image gallery with zoom, 3D tour embed, AI condition assessment panel, ownership timeline visualization, distress stack visualization, deal calculator inline, comparable sales map, title risk panel, smart contract status, bid history, AI score breakdown with factor visualization, share buttons (email, social, copy link), and a sticky sidebar with key stats and CTA." },
      { title: "Dashboard UX Optimization", prompt: "Optimize the UX of every dashboard (investor, seller, agent, admin). Ensure: clear information hierarchy, progressive disclosure (show summary, expand for details), contextual help tooltips, keyboard shortcuts for power users, customizable layouts (drag-and-drop widgets), recent activity feeds, and quick-action toolbars. Add a 'Customize Dashboard' button. Test with real users and iterate." },
    ],
  },
];