// Agent Tool Registry — the complete catalog of tools available to the
// digital workforce. Organized by category: Google Workspace, daily
// business, web account creation, crypto/wallets, and media generation.
//
// Each tool defines: id, name, description, category, the execution
// method (connector, function, browser, or gateway), and input schema.
// The agentToolGenerator backend function uses this registry to list
// available tools and execute them on behalf of digital agents.

export const TOOL_CATEGORIES = [
  {
    id: "google_workspace",
    label: "Google Workspace",
    icon: "Mail",
    description: "Email, calendar, documents, spreadsheets, drive, and tasks — the full Google Workspace suite for conducting business.",
    tools: [
      {
        id: "gmail_send",
        name: "Send Email (Gmail)",
        description: "Send an email through the connected Gmail account",
        method: "connector",
        connector: "gmail",
        inputs: { to: "string", subject: "string", body: "string" },
        status: "needs_auth",
      },
      {
        id: "gmail_read",
        name: "Read Emails (Gmail)",
        description: "List and read recent emails from Gmail inbox",
        method: "connector",
        connector: "gmail",
        inputs: { max_results: "number" },
        status: "needs_auth",
      },
      {
        id: "gcal_list",
        name: "List Calendar Events",
        description: "List upcoming Google Calendar events",
        method: "connector",
        connector: "googlecalendar",
        inputs: { max_results: "number" },
        status: "authorized",
      },
      {
        id: "gcal_create",
        name: "Create Calendar Event",
        description: "Create a new event on Google Calendar",
        method: "connector",
        connector: "googlecalendar",
        inputs: { summary: "string", start_time: "string", end_time: "string", description: "string" },
        status: "authorized",
      },
      {
        id: "gsheets_read",
        name: "Read Spreadsheet",
        description: "Read data from a Google Sheets spreadsheet",
        method: "connector",
        connector: "googlesheets",
        inputs: { spreadsheet_id: "string", range: "string" },
        status: "authorized",
      },
      {
        id: "gsheets_write",
        name: "Write to Spreadsheet",
        description: "Write data to a Google Sheets spreadsheet",
        method: "connector",
        connector: "googlesheets",
        inputs: { spreadsheet_id: "string", range: "string", values: "array" },
        status: "authorized",
      },
      {
        id: "gdocs_create",
        name: "Create Google Doc",
        description: "Create a new Google Docs document",
        method: "connector",
        connector: "googledocs",
        inputs: { title: "string", content: "string" },
        status: "needs_auth",
      },
      {
        id: "gdrive_list",
        name: "List Drive Files",
        description: "List files in Google Drive",
        method: "connector",
        connector: "googledrive",
        inputs: { query: "string", max_results: "number" },
        status: "needs_auth",
      },
      {
        id: "gtasks_list",
        name: "List Google Tasks",
        description: "List tasks from Google Tasks",
        method: "connector",
        connector: "googletasks",
        inputs: { tasklist_id: "string" },
        status: "needs_auth",
      },
      {
        id: "gtasks_create",
        name: "Create Google Task",
        description: "Create a new task in Google Tasks",
        method: "connector",
        connector: "googletasks",
        inputs: { title: "string", notes: "string", due_date: "string" },
        status: "needs_auth",
      },
    ],
  },
  {
    id: "daily_business",
    label: "Daily Business Tools",
    icon: "Briefcase",
    description: "Core tools the digital workforce uses every day — CRM, AI reasoning, web search, and platform communications.",
    tools: [
      {
        id: "ai_reasoning",
        name: "AI Reasoning Engine",
        description: "Invoke the Vercel AI Gateway for complex reasoning, analysis, and decision-making",
        method: "gateway",
        inputs: { prompt: "string", model: "string" },
        status: "available",
      },
      {
        id: "web_search",
        name: "Web Search (Perplexity)",
        description: "Search the web for real-time information and intelligence",
        method: "gateway",
        inputs: { query: "string" },
        status: "available",
      },
      {
        id: "platform_email",
        name: "Send Platform Email",
        description: "Send email through the platform's built-in email integration",
        method: "integration",
        integration: "SendEmail",
        inputs: { to: "string", subject: "string", body: "string" },
        status: "credits_exhausted",
      },
      {
        id: "hubspot_crm",
        name: "HubSpot CRM",
        description: "Manage contacts, deals, and pipeline in HubSpot CRM",
        method: "connector",
        connector: "hubspot",
        inputs: { action: "string", data: "object" },
        status: "needs_auth",
      },
      {
        id: "agent_think",
        name: "Agent Think",
        description: "Invoke another digital agent to reason about a task",
        method: "function",
        function: "agentThink",
        inputs: { agent_id: "string", instruction: "string" },
        status: "available",
      },
    ],
  },
  {
    id: "web_accounts",
    label: "Web Account Creation",
    icon: "Globe",
    description: "Create accounts on virtually any website, social media platform, or online service using the browser automation engine.",
    tools: [
      {
        id: "create_web_account",
        name: "Create Web Account (Any Site)",
        description: "Automate account creation on any website using the browser engine",
        method: "browser",
        inputs: { url: "string", email: "string", password: "string", name: "string" },
        status: "available",
      },
      {
        id: "create_facebook_page",
        name: "Create Facebook Page",
        description: "Create a Facebook business page for the agent or business",
        method: "browser",
        inputs: { page_name: "string", category: "string", description: "string" },
        status: "available",
      },
      {
        id: "create_instagram_account",
        name: "Create Instagram Account",
        description: "Create an Instagram business account",
        method: "browser",
        inputs: { username: "string", email: "string", password: "string" },
        status: "available",
      },
      {
        id: "create_linkedin_page",
        name: "Create LinkedIn Page",
        description: "Create a LinkedIn company page",
        method: "browser",
        inputs: { company_name: "string", industry: "string", description: "string" },
        status: "available",
      },
      {
        id: "create_twitter_account",
        name: "Create Twitter/X Account",
        description: "Create a Twitter/X account for the agent",
        method: "browser",
        inputs: { username: "string", email: "string", password: "string" },
        status: "available",
      },
      {
        id: "create_tiktok_account",
        name: "Create TikTok Account",
        description: "Create a TikTok business account",
        method: "browser",
        inputs: { username: "string", email: "string", password: "string" },
        status: "available",
      },
      {
        id: "create_discord_server",
        name: "Create Discord Server",
        description: "Create a Discord server for community engagement",
        method: "browser",
        inputs: { server_name: "string", region: "string" },
        status: "available",
      },
      {
        id: "create_youtube_channel",
        name: "Create YouTube Channel",
        description: "Create a YouTube channel for media distribution",
        method: "browser",
        inputs: { channel_name: "string", description: "string" },
        status: "available",
      },
    ],
  },
  {
    id: "crypto",
    label: "Crypto & Wallets",
    icon: "Wallet",
    description: "Create cryptocurrency wallets, exchange accounts, and manage digital assets on the Polygon blockchain.",
    tools: [
      {
        id: "create_wallet",
        name: "Create Crypto Wallet",
        description: "Generate a new Ethereum/Polygon wallet with private key and address",
        method: "function",
        function: "generateWallet",
        inputs: { label: "string" },
        status: "available",
      },
      {
        id: "import_wallet",
        name: "Import Wallet",
        description: "Import an existing wallet using a private key or mnemonic",
        method: "function",
        function: "importWallet",
        inputs: { private_key: "string", label: "string" },
        status: "available",
      },
      {
        id: "create_exchange_account",
        name: "Create Exchange Account",
        description: "Create an account on a crypto exchange (Coinbase, Binance, Kraken)",
        method: "browser",
        inputs: { exchange: "string", email: "string", password: "string" },
        status: "available",
      },
      {
        id: "deploy_smart_contract",
        name: "Deploy Smart Contract",
        description: "Deploy an escrow smart contract on the Polygon blockchain",
        method: "function",
        function: "deploySmartContract",
        inputs: { property_id: "string", terms: "object" },
        status: "available",
      },
    ],
  },
  {
    id: "media",
    label: "Image & Media Creation",
    icon: "Image",
    description: "Generate AI images, agent avatars, social media graphics, and visual content.",
    tools: [
      {
        id: "generate_image",
        name: "Generate Image (AI)",
        description: "Generate a custom image using the AI Gateway",
        method: "gateway_image",
        inputs: { prompt: "string", width: "number", height: "number" },
        status: "available",
      },
      {
        id: "generate_agent_avatar",
        name: "Generate Agent Avatar",
        description: "Generate a professional headshot/avatar for a digital agent",
        method: "gateway_image",
        inputs: { agent_name: "string", style: "string" },
        status: "available",
      },
      {
        id: "generate_social_graphic",
        name: "Generate Social Media Graphic",
        description: "Generate a social media post image or banner",
        method: "gateway_image",
        inputs: { platform: "string", prompt: "string" },
        status: "available",
      },
      {
        id: "generate_business_logo",
        name: "Generate Business Logo",
        description: "Generate a business logo for the agent or company",
        method: "gateway_image",
        inputs: { business_name: "string", style: "string" },
        status: "available",
      },
    ],
  },
];

// Flatten all tools for quick lookup
export const ALL_TOOLS = TOOL_CATEGORIES.flatMap(cat =>
  cat.tools.map(t => ({ ...t, category: cat.id, category_label: cat.label }))
);

export function getToolById(id) {
  return ALL_TOOLS.find(t => t.id === id);
}